name: List Changed Files

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.6
      with:
        fetch-depth: 0

    - name: Get list of changed files
      id: pr_files
      run: |
        echo "files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})" >> $GITHUB_OUTPUT

    - name: Comment PR
      uses: actions/github-script@v5
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const output = `${{ steps.pr_files.outputs.files }}`;
          const issue_number = context.issue.number;
          const octokit = github.getOctokit(github_token);
          octokit.rest.issues.createComment({
            ...context.repo,
            issue_number,
            body: `Changed files: \n${output.split('\n').join('\n')}`
          });